[package]
name = "boids_rs"
version = "0.1.0"
authors = ["Jorge Yanar <jorgeyanar@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "*"
piston_window = "0.110.0"
